<a href="https://colab.research.google.com/github/golamrabbanirifat41/Data-Science-Study/blob/main/session_13_numpy_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


It can be called vector<br>np.array is a basic function which create array

In [2]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


It can be called matrix.<br>
2 rows and 3 columns


In [3]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


It also called Tensor

In [4]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
#boolean type
np.array([1,2,3,0],dtype=bool)

array([ True,  True,  True, False])

In [6]:
# np.arange--> also used for creating array
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

The functionality is same as **"range"** function

**reshape -->convert one given shaped numpy array to different **

In [7]:
# with reshape
np.arange(1,11).reshape(2,5)#creating a 2 row and 5 columb array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
np.arange(1,13).reshape(5,5)

ValueError: cannot reshape array of size 12 into shape (5,5)

5x5 is not possible because 5x5!=13<br> 13 item can't create a array of 5 row and 5 column

In [ ]:
# with reshape
np.arange(16).reshape(2,2,2,2)#####################################Problem###########################

In [ ]:
# np.ones and np.zeros
np.ones((3,4))

**Use-case**-->To initialize arrays-->neural networks<br>
**np.zeros,np.random,np.ones --> same **

In [ ]:
np.zeros((3,4))

In [ ]:
# np.random
np.random.random((3,4))



---



---

np.linspace-->linearly space

In [ ]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

In [9]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [10]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [11]:
# ndim
a3.ndim

3

In [12]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [14]:
# itemsize
a3.itemsize

8

In [15]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [16]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [17]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [19]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [20]:
# vector operations
# arithmetic
a1 ** a2
#0^12=0
#1^13=1
#2^14=16384
#3^15=14348907


array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [21]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[100.,  37.,  93.],
       [  6.,  79.,  57.],
       [ 85.,  40.,  13.]])

In [22]:
# max/min/sum/prod
# 0 -> col and 1 -> row
print(np.prod(a1,axis=0))
print(np.sum(a1,axis=1))
print(np.max(a1))
print(np.min(a1,axis=0))

[ 51000. 116920.  68913.]
[230. 142. 138.]
100.0
[ 6. 37. 13.]


In [23]:
# mean/median/std/var
np.var(a1,axis=1)

array([794.88888889, 934.88888889, 882.        ])

In [24]:
# trigonomoetric functions
np.sin(a1)

array([[-0.50636564, -0.64353813, -0.94828214],
       [-0.2794155 , -0.44411267,  0.43616476],
       [-0.17607562,  0.74511316,  0.42016704]])

In [25]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [26]:
# log and exponents
np.exp(a1)

array([[2.68811714e+43, 1.17191424e+16, 2.45124554e+40],
       [4.03428793e+02, 2.03828107e+34, 5.68572000e+24],
       [8.22301271e+36, 2.35385267e+17, 4.42413392e+05]])

In [27]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[72., 67., 13.],
       [30., 45., 20.]])

### Indexing and Slicing

In [28]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a2[1,0]

np.int64(4)

In [32]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [33]:
a3[1,0,1]

np.int64(5)

In [34]:
a3[1,1,0]

np.int64(6)

In [35]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a1[2:5:2]

array([2, 4])

In [37]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [39]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [40]:
a2[1,::3]

array([4, 7])

In [41]:
a2[0,:]

array([0, 1, 2, 3])

In [42]:
a2[:,2]

array([ 2,  6, 10])

In [43]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [44]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [45]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [46]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [47]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [48]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [49]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
for i in a2:
  print(i)
  print("=====")

[0 1 2 3]
=====
[4 5 6 7]
=====
[ 8  9 10 11]
=====


In [51]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [63]:
for i in a3:
  print(i)
  print("====")

[[0 1 2]
 [3 4 5]
 [6 7 8]]
====
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
====
[[18 19 20]
 [21 22 23]
 [24 25 26]]
====


In [53]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [54]:
# reshape

In [64]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
# Transpose= convert row to column and convert column to row.

a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [70]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [56]:
# ravel-- convert to 1D array
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [57]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [58]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [78]:
# Vertical stacking
a6=np.vstack((a4,a5))
a6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [60]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
# vertical splitting

In [79]:
a6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [83]:
np.vsplit(a6,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [85]:
np.vsplit(a6,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]